project_id          = "<your-project-id>"
env                 = "dev"
slack_channel_name  = "#notification-airflow-dev"
region              = "us-west"
service_account     = "<your-project-id>d@<your-project-id>d.iam.gserviceaccount.com"